### PR TITLE
Added ElmType Instances to Int8-Int64

### PR DESCRIPTION
**Pull request by expipiplus1**
cherry picked from @krisajenkins's master

### CODE REVIEW

**Comment by mattjbray** [comment]
Thanks. `servant-elm` is currently using the `experimental-v2` branch though, did you mean to open the PR against that branch?

**Comment by expipiplus1** [comment]
oh perhaps. The branching situation is quite complex :(

**Comment by mattjbray** [comment]
Yes it's unfortunate. Hopefully we can get it sorted out soon.

**Comment by expipiplus1** [comment]
I'll reopen a PR on the correct branch.

**Comment by expipiplus1** [comment]
@mattjbray it seems to actually be using the `render-ref` branch. Should I open a PR there too/instead?

**Pull request closed without merging**
